### ISSUE TITLE
Can we use this package to model flow with different origins and destinations?

### ISSUE THREAD

**Issue by tanhuajin** [LukeCe/spflow#11]
The origin and destination networks are the same in this model. Can we use this package to model flow with different origins and destinations? For example, the origins and destinations are different shapefile?

**Comment by LukeCe** [comment]
Hello,

And sorry for my late reply.

The case you mentioned has been labeled the rectangular case (see [Laurent et al. (2023)](https://doi.org/10.1111/gean.12358)), and the package implements it.

If some flows in your data are zero or unobserved, you have to use the development version of the package, and I recommend you read my reply to #12
